#!/usr/bin/env bash
##
## slub/pvldb -- Bibliometric Analysis of PVLDB
## Copyright (c) 2022 SLUB Dresden
##
## This file is part of slub/pvldb.
##
## slub/pvldb is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## slub/pvldb is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
## See the GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with slub/pvldb. If not, see <https://www.gnu.org/licenses/>.
##
mkdir -p data
curl "https://api.crossref.org/journals/2150-8097?mailto=bibliometrie@slub-dresden.de" | jq . > data/crossref_journals_2150-8097.json
curl "https://api.journalsdb.org/journals/2150-8097" | jq . > data/journalsdb_journals_2150-8097.json
curl "https://api.openalex.org/journals/V4210226185?mailto=bibliometrie@slub-dresden.de" | jq . > data/openalex_journals_V4210226185.json
